version: "3.9"  # optional since v1.27.0
name: app
services:
  app: 
    image: dotnet-vue-ts-docker-sqlite-fullstack-dev
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./data.sqlite3
        target: /app/data.sqlite3